#Name=input("enter the your full name: ")
#phone_number=input("enter your phone number:")
#result = len(Name)
#result= Name.find("A")
#result= Name.rfind("Q")
#Name=Name.capitalize()
#Name=Name.upper()
#Name=Name.lower()
#result=Name.isdigit()
#result=Name.isalpha()
#result=phone_number.count("9")
#phone_number=phone_number.replace("a","s")
#print(phone_number)
print(help(str))
